### PR TITLE
Send notification to the new imported user

### PR DESCRIPTION
**Pull request by mako321**

### CODE REVIEW

**Comment by qunabu** [comment]
@pa-cholek @HerbertIV you think it's ok ? 
imho account confirmed event would do the same

**Comment by HerbertIV** [comment]
> @pa-cholek @HerbertIV you think it's ok ? imho account confirmed event would do the same

Yes, I think adding this to a confirmed event will have the same effect

**Comment by pa-cholek** [comment]
> @pa-cholek @HerbertIV you think it's ok ? imho account confirmed event would do the same

It depends on what should be the content of email notification for this event, if we want to send two different messages to users that were imported and to users whose accounts were confirmed then we need two separate events?

**Comment by mako321** [comment]
The message should be different. Account is already verified.

**Pull request merged**
